apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      prometheusremotewrite:
        endpoint: {{ .Values.victoria.metrics.url }}/api/v1/write
      otlphttp/vlogs:
        endpoint: "http://victoria-logs:9428/insert/jsonline"
        encoding: json
        tls:
          insecure: true
      otlp/vtraces:
        endpoint: victoria-traces:8429
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/vlogs]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/vtraces]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          args: ["--config=/etc/otel/config.yaml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/otel/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  selector:
    app: otel-collector
  ports:
    -   name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
    -   name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
