apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-traces
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-traces
  template:
    metadata:
      labels:
        app: victoria-traces
    spec:
      containers:
        - name: victoria-traces
          image: {{ .Values.victoria.traces.image | quote }}
          args:
            - -storageDataPath=/vtraces
            - -httpListenAddr=:8429
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: http
              containerPort: 8429
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-traces
  namespace: observability
spec:
  selector:
    app: victoria-traces
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http
      port: 8429
      targetPort: 8429
      protocol: TCP
