apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/
  
    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/
  
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/