apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: |
    title: Running Dashboard
    theme: dark
    color: slate
    layout:
      Training:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 3
      Services:
        style: row
        columns: 3
    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey

