apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
   widgets.yaml: |
    - greeting:
        text_size: xl
        text: Salut everybody tout le monde ! Ça y est, c'est mardi, c'est bientôt le weekend !

    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: duckduckgo
        target: _blank

    - openmeteo:
        label: FRONCE
        latitude: 45.75616795876988
        longitude: 4.847809439426622
        timezone: Europe/Paris # optional
        units: metric # or imperial
        cache: 1 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
