namespace: observability

grafana:
  image: grafana/grafana:latest
  adminPassword: admin

otelCollector:
  image: otel/opentelemetry-collector:latest

victoria:
  metrics:
    image: victoriametrics/victoria-metrics:latest
    url: http://127.0.0.1/:8428
  logs:
    image: victoriametrics/victoria-logs:latest
    url: http://127.0.0.1/:9428
  traces:
    image: victoriametrics/victoria-traces:latest
