apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homepage
  namespace: homepage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 150m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
