apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: homepage:otel
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "localhost:5000,$(MY_POD_IP):4000,$(MY_POD_IP):3000" # See gethomepage.dev/installation/#homepage_allowed_hosts . Value before the comma is required for the k8s probe
            - name: OTEL_SERVICE_NAME
              value: homepage
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=dev,k8s.namespace.name=homepage
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /app/config/proxmox.yaml
              name: homepage-config-proxmox
              subPath: proxmox.yaml
            - mountPath: /app/config/custom.css
              name: homepage-config-js-css
              subPath: custom.css
            - mountPath: /app/config/custom.js
              name: homepage-config-js-css
              subPath: custom.js
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config-bookmarks
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config-docker
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config-kubernetes
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config-services
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config-settings
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config-widgets
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
            - mountPath: /app/public/images
              name: images
      volumes:
      - configMap:
          name: homepage-docker
        name: homepage-config-docker
      - configMap:
          name: homepage-kubernetes
        name: homepage-config-kubernetes
      - configMap:
          name: homepage-services
        name: homepage-config-services
      - configMap:
          name: homepage-settings
        name: homepage-config-settings
      - configMap:
          name: homepage-widgets
        name: homepage-config-widgets
      - configMap:
          name: homepage-bookmarks
        name: homepage-config-bookmarks
      - configMap:
          name: homepage-js-css
        name: homepage-config-js-css
      - configMap:
          name: homepage-proxmox
        name: homepage-config-proxmox
      - emptyDir: {}
        name: logs
      - persistentVolumeClaim:
          claimName: homepage-images-pvc
        name: images
