apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-services
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  services.yaml: |
    - Planning entrainement:
        - Google Calendar:
            icon: google-calendar
            widget:
              type: calendar
              firstDayInWeek: monday
              view: monthly
              maxEvents: 10 # optional - defaults to 10
              showTime: true # optional - show time for event happening today - defaults to false
              previousDays: 3 # optional - shows events since three days ago - defaults to 0
              timezone: Europe/Paris
    - Social:
        - MAMOT Mastodon:
            widget:
              type: mastodon
              url: https://mamot.fr
        - Strava:
            icon: strava.png
            href: https://www.strava.com
            description: Mes activités sportives
            widget:
              type: strava
              url: https://www.strava.com/api/v3
              client_id: "218169"
              client_secret: "ffa857a769841c5cdf934ed1b5b065e9505d6363"
              refresh_token: "0c3bcf13fc4493cd9dbaf7a393f21811578d28fd"
              athlete_id: "182964604"

    - Observability:
        - Grafana:
            href: http://grafana.observability.svc.cluster.local:4000
            description: Dashboards & logs
            icon: grafana.png
            widget:
              type: grafana
              url: http://grafana.observability.svc.cluster.local:4000
              username: admin
              password: admin
    - Liens utiles:
        - Garmin-connect:
            href: https://connect.garmin.com/modern
            description: Mes données de santé
            icon: garmin-connect.png
        - Deezer:
            href: https://www.deezer.com
            description: Musique en streaming
            icon: deezer.png

    - Billeterie:
        - widget:
            type: iframe
            name: billetterie-ol
            href: https://billetterie.ol.fr/fr/calendrier
            description: Billets pour les matchs de l'Olympique Lyonnais
            refreshInterval: 3600 # in seconds, optional
            allowFullscreen: true # optional, defaults to false
            referrerPolicy: same-origin # optional, defaults to no-referrer
